# Generated by Django 5.2.16 on 2026-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='preferred_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
