# Generated by Django 5.2.16 on 2026-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='otp_hash',
            field=models.CharField(default='dummy_hash', max_length=128),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'is_used', '-expires_at'], name='users_otpve_user_id_ba7b25_idx'),
        ),
    ]
